const movements = [
  { slug: "air-bike", name: "Air Biking/Assault Biking" },
  { slug: "air-squat", name: "Air Squat" },
  { slug: "arch-up-superman-hold", name: "Arch Up/Arch Hold (Superman)" },
  { slug: "back-extension", name: "Back Extension/Hip Extension" },
  { slug: "back-scale", name: "Back Scale" },
  { slug: "back-squat", name: "Back Squat" },
  { slug: "back-tuck", name: "Back Tuck" },
  { slug: "backward-roll", name: "Backward Roll" },
  { slug: "ball-slams", name: "Ball Slam" },
  { slug: "bear-crawl", name: "Bear Crawl" },
  { slug: "bench-press", name: "Bench Press" },
  { slug: "bent-over-row", name: "Bent Over Row" },
  { slug: "bike-bicycle", name: "Biking (Cycling)" },
  { slug: "box-jump", name: "Box Jump" },
  { slug: "box-step-up", name: "Box Step-Up" },
  { slug: "broad-jump", name: "Broad Jump" },
  { slug: "burpee", name: "Burpee" },
  { slug: "candlestick", name: "Candlestick" },
  { slug: "clean", name: "Clean" },
  { slug: "crossover", name: "Crossover" },
  { slug: "curl", name: "Curl" },
  { slug: "deadlift", name: "Deadlift" },
  { slug: "devil-press", name: "Devil Press" },
  { slug: "dip", name: "Dip/Ring Dip/Tricep Dip" },
  { slug: "double-under", name: "Double-Under" },
  { slug: "dumbbell-swing", name: "Dumbbell Swing" },
  { slug: "farmers-carry", name: "Farmer's Carry" },
  { slug: "firemans-carry", name: "Fireman's Carry" },
  { slug: "floor-wiper", name: "Floor Wiper" },
  { slug: "flutterkick", name: "Flutter Kick/Leg Raise" },
  { slug: "forward-roll", name: "Forward Roll" },
  { slug: "front-scale", name: "Front Scale" },
  { slug: "front-squat", name: "Front Squat" },
  { slug: "ghd-sit-up", name: "GHD Sit-Up" },
  { slug: "goblet-squat", name: "Goblet Squat" },
  { slug: "good-mornings", name: "Good Morning" },
  { slug: "grasshopper", name: "Grasshopper" },
  { slug: "ground-to-overhead", name: "Ground-to-Overhead" },
  { slug: "hack-squat", name: "Hack Squat" },
  { slug: "hammer-strike", name: "Hammer Strike" },
  { slug: "handstand-hold", name: "Handstand Hold" },
  { slug: "handstand-push-up", name: "Handstand Push-Up" },
  { slug: "handstand-walk", name: "Handstand Walk" },
  { slug: "hang-hold", name: "Hang Hold" },
  { slug: "heel-clap", name: "Heel Clap" },
  { slug: "hollow-hold", name: "Hollow Hold" },
  { slug: "hollow-rock", name: "Hollow Rock" },
  { slug: "inchworm", name: "Inchworm" },
  { slug: "inverted-burpee", name: "Inverted Burpee" },
  { slug: "inverted-hang", name: "Inverted Hang" },
  { slug: "jerk", name: "Jerk" },
  { slug: "jumping-jack", name: "Jumping Jack" },
  { slug: "kettlebell-swing", name: "Kettlebell Swing" },
  { slug: "kettlebell-tater", name: "Kettlebell Tater" },
  { slug: "l-sit", name: "L-Sit" },
  { slug: "lateral-jump", name: "Lateral Jump" },
  { slug: "lateral-raise", name: "Lateral Raise" },
  { slug: "lunge", name: "Lunge" },
  { slug: "man-maker", name: "Man Maker" },
  { slug: "monkey-bar-traverse", name: "Monkey Bar Traverse" },
  { slug: "mountain-climber", name: "Mountain Climber" },
  { slug: "muscle-up", name: "Muscle-Up" },
  { slug: "overhead-squat", name: "Overhead Squat" },
  { slug: "paddleboard", name: "Paddleboard" },
  { slug: "parallette-pass-through", name: "Parallette Pass-Through" },
  { slug: "pegboard-ascent", name: "Pegboard Ascent" },
  { slug: "pistol", name: "Pistol" },
  { slug: "plank-hold", name: "Plank Hold" },
  { slug: "pull-up", name: "Pull-Up" },
  { slug: "push-press", name: "Push Press" },
  { slug: "push-up", name: "Push-Up" },
  { slug: "ring-row", name: "Ring Row" },
  { slug: "rope-climb", name: "Rope Climb" },
  { slug: "row", name: "Row (Rowing)" },
  { slug: "run", name: "Run (Running)" },
  { slug: "russian-twist", name: "Russian Twist" },
  { slug: "shoulder-to-overhead", name: "Shoulder-to-Overhead" },
  { slug: "shuttle-run", name: "Shuttle Run" },
  { slug: "jump-rope-singles", name: "Single-Under" },
  { slug: "sit-up", name: "Sit-Up" },
  { slug: "ski", name: "Ski (Skiing on Ski Erg)" },
  { slug: "sled-pull", name: "Sled Pull" },
  { slug: "sled-push-prowler-push", name: "Sled Push (Prowler Push)" },
  { slug: "snatch", name: "Snatch" },
  { slug: "snatch-balance", name: "Snatch Balance" },
  { slug: "sots-press", name: "Sots Press" },
  { slug: "strict-press", name: "Strict Press (Shoulder Press)" },
  { slug: "sumo-deadlift-high-pull", name: "Sumo Deadlift High-Pull" },
  { slug: "swim", name: "Swim/Swimming" },
  { slug: "thruster", name: "Thruster" },
  { slug: "tip-touch", name: "Tip Touch" },
  { slug: "tire-flip", name: "Tire Flip" },
  { slug: "toes-to-bar", name: "Toes-to-Bar/Knees-to-Elbows" },
  { slug: "triple-under", name: "Triple-Under" },
  { slug: "tuck-jump", name: "Tuck Jump" },
  { slug: "tuck-up", name: "Tuck Up" },
  { slug: "turkish-get-up", name: "Turkish Get-Up" },
  { slug: "up-down", name: "Up-Down" },
  { slug: "v-up", name: "V-Up" },
  { slug: "wall-ball-shot", name: "Wall Ball Shot" },
  { slug: "wall-climb", name: "Wall Climb/Wall Walk" },
  { slug: "wall-sit", name: "Wall Sit" },
  { slug: "weighted-walk-run", name: "Weighted Walk/Run" },
  { slug: "yoke-carry", name: "Yoke Carry" }
    ];


const equipments = [
  { slug: "abmat", name: "AbMat" },
  { slug: "air-bike", name: "Air Bike (Assault Bike)" },
  { slug: "axle-bar", name: "Axle Bar" },
  { slug: "barbell", name: "Barbell" },
  { slug: "bench", name: "Bench" },
  { slug: "bike", name: "Bike (Bicycle)" },
  { slug: "bikeerg", name: "BikeErg / Stationary Bike" },
  { slug: "box", name: "Box" },
  { slug: "d-ball", name: "Dead Ball (D-Ball)" },
  { slug: "dip-bars", name: "Dip Bars" },
  { slug: "dumbbells", name: "Dumbbell(s)" },
  { slug: "ghd-machine", name: "GHD Machine" },
  { slug: "rings", name: "Gymnastic Rings" },
  { slug: "jump-rope", name: "Jump Rope" },
  { slug: "keg", name: "Keg" },
  { slug: "kettlebells", name: "Kettlebell(s)" },
  { slug: "log", name: "Log" },
  { slug: "medicine-ball", name: "Medicine Ball (Wall Ball)" },
  { slug: "monkey-bars", name: "Monkey Bars" },
  { slug: "paddleboard", name: "Paddleboard" },
  { slug: "parallettes", name: "Parallettes" },
  { slug: "peg-board", name: "Peg Board" },
  { slug: "plate", name: "Plate(s)" },
  { slug: "pool", name: "Pool/Open Water" },
  { slug: "pull-up-bar", name: "Pull-Up Bar" },
  { slug: "pvc-pipe", name: "PVC Pipe" },
  { slug: "ramp", name: "Ramp" },
  { slug: "rope", name: "Rope" },
  { slug: "rower", name: "Rower" },
  { slug: "ruck", name: "Ruck" },
  { slug: "sandbag", name: "Sandbag" },
  { slug: "skierg", name: "SkiErg" },
  { slug: "sled", name: "Sled (Prowler)" },
  { slug: "sledgehammer", name: "Sledgehammer" },
  { slug: "stairs", name: "Stairs" },
  { slug: "tire", name: "Tire" },
  { slug: "treadmill", name: "Treadmill" },
  { slug: "wall", name: "Wall (Obstacle)" },
  { slug: "weight-rack", name: "Weight Rack" },
  { slug: "weight-vest", name: "Weight Vest" },
  { slug: "wheel-barrow", name: "Wheel Barrow" },
  { slug: "yoke", name: "Yoke" }
];

  // 이하 기존 JS 코드 전체 복붙